"""add foreign key to post

Revision ID: ec0a5f5a7e94
Revises: 9dee06e54968
Create Date: 2025-02-26 04:45:17.260197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ec0a5f5a7e94"
down_revision: Union[str, None] = "9dee06e54968"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("user_uid", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "posts", "users", ["user_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "user_uid")
    # ### end Alembic commands ###
