"""fix tag table

Revision ID: 2a6f8668a8d5
Revises: abb2cc9582a6
Create Date: 2025-02-26 05:08:28.072687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a6f8668a8d5'
down_revision: Union[str, None] = 'abb2cc9582a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tagpostlinks', 'posts', ['post_uid'], ['uid'])
    op.create_foreign_key(None, 'tagpostlinks', 'tags', ['tag_uid'], ['uid'])
    op.drop_constraint('tags_post_uid_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'post_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('post_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_post_uid_fkey', 'tags', 'posts', ['post_uid'], ['uid'])
    op.drop_constraint(None, 'tagpostlinks', type_='foreignkey')
    op.drop_constraint(None, 'tagpostlinks', type_='foreignkey')
    # ### end Alembic commands ###
