"""fix tag table

Revision ID: 79c0f92df837
Revises: ec0a5f5a7e94
Create Date: 2025-02-26 04:58:28.409922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79c0f92df837'
down_revision: Union[str, None] = 'ec0a5f5a7e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('tags', sa.Column('post_uid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tags', 'posts', ['post_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'post_uid')
    op.alter_column('posts', 'user_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
