class AppException(Exception):
    """This is the base Error for the application"""


class InterServerException(AppException):
    """This is the error generated by the server"""


# auths
class UserAlreadyExist(AppException):
    """User is already exist in database with same email"""


class UserNotFound(AppException):
    """User with given credentials does not exist"""


class UserNameAlreadyTaken(AppException):
    """User with given username is already exist in database"""


class InvalidOTP(AppException):
    """User had provide the invalid otp"""


class InvalidToken(AppException):
    """User had provide the invalid jwt token"""


class ExpiredToken(AppException):
    """User had provide the expired jwt token"""


class InvalidCredentials(AppException):
    """User had provide the invalid credentials"""


class AccessTokenRequired(AppException):
    """User had provided refresh token in place of access token"""


class RefreshTokenRequired(AppException):
    """User had provided access token in place of refresh token"""


class UnAuthenticated(AppException):
    """User does't provided the Authorization header"""


class AlreadyFollowed(AppException):
    """User try to follow user who he had already followed"""


class InvalidOperation(AppException):
    """User try to perform silly operations"""
